import React from "react";
import { useSummaries } from "../hooks/useSummaries";
import { numberValue } from "../utils/formatters";

export default function Reports() {
  const { summaries } = useSummaries();

  const rows = [
    ["Daily", summaries.daily],
    ["Weekly", summaries.weekly],
    ["Monthly", summaries.monthly],
    ["Yearly", summaries.yearly],
  ];

  return (
    <main className="dashboard-page">
      <section className="hero-panel">
        <div>
          <p className="eyebrow">Reports</p>
          <h1>Energy consumption reports</h1>
          <p className="hero-subtitle">
            Summary reports generated by the AI engine from Firebase history.
          </p>
        </div>
      </section>

      <section className="panel-card">
        <div className="panel-title-row">
          <div>
            <p className="eyebrow">Consumption</p>
            <h3>Summary table</h3>
          </div>
        </div>

        <div className="report-table">
          {rows.map(([label, row]) => (
            <div className="report-row" key={label}>
              <strong>{label}</strong>
              <span>{numberValue(row?.kwh_used, 3)} kWh</span>
              <span>Avg {numberValue(row?.average_power_w, 1)} W</span>
              <span>Peak {numberValue(row?.peak_power_w, 1)} W</span>
              <span>Samples {row?.sample_count || 0}</span>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
