[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    mandulaj/PZEM-004T-v30
    bodmer/TFT_eSPI
    bblanchon/ArduinoJson

build_flags =
    -I include
    -I src
    -I tft
    -include TFT_USER_SETUP.h
